name: Deploy
description: "Deploys the artifacts for a release and generates the documentation"

inputs:
  artifact-name:
    required: true
    description: "Name of the artifact to deploy"
  nuget-api-key:
    required: true
    description: "NuGet API key to publish the package"
  docs-output-prefix:
    required: true
    description: "Path prefix where the docs will be generated"
  github-token:
    required: true
    description: "GitHub token to run the deployment and docs generation"
  dry-run:
    required: true
    description: "Dry run (doesn't actually publish anything)"

runs:
  using: composite
  steps:
  - name: Download artifacts
    uses: actions/download-artifact@v3
    with:
      name: ${{ inputs.artifact-name }}
      path: /tmp/artifacts
  - name: Deploy
    shell: bash
    env:
      GH_TOKEN: ${{ inputs.github-token }}
      NUGET_SERVER_URL: https://www.nuget.org/
      NUGET_API_KEY: ${{ inputs.nuget-api-key }}
    run: |
      if [[ "${{ inputs.dry-run }}" == "true" ]]; then
        DRY_RUN_OPTION=--dry-run
      fi
      dotnet run --project tools-shared/FakeItEasy.Deploy -- $DRY_RUN_OPTION -r "${{ github.repository }}" -t "${{ github.ref_name }}" -a "/tmp/artifacts/output"
  - name: Trigger docs generation
    shell: bash
    env:
      GH_TOKEN: ${{ inputs.github-token }}
    run: |
      publishMode=auto-merge
      if [[ "${{ inputs.dry-run }}" == "true" ]]; then
        publishMode=none
      fi
      gh workflow run generate-docs.yml \
        -R FakeItEasy/fakeiteasy.github.io \
        -f output-prefix=${{ inputs.docs-output-prefix }} \
        -f version=${{ github.ref_name }} \
        -f source-repo=${{ github.repository }} \
        -f source-ref=${{ github.ref_name }} \
        -f publish-mode=$publishMode
